Handle lsk
farao-community/gridcapa-cse pull request #96
Opened 2022-08-16 14:01 UTC by TheoPascoli

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-08-18 13:01 UTC, TheMaskedTurtle requested changes

2022-08-18 13:34 UTC, TheMaskedTurtle requested changes

2022-08-18 13:34 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
> +    private void handleLsk(Network network, ZonalData<Scalable> zonalScalable, ProcessType processType) {
Maybe rename this method, something like addScalableOnLoads or stackScalableOnLoads

2022-08-23 07:30 UTC, TheoPascoli commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
> +    private boolean isLoadCorrespondingToTheZone(Load load, String zone) {
clean

2022-08-29 07:54 UTC, benrejebmoh submitted a review, later dismissed

2022-08-29 08:00 UTC, TheMaskedTurtle requested changes

2022-08-29 08:00 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
> +                getNetworkValidator(cseRequest, cseData));
Please remove the empty spaces here

2022-08-29 08:00 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
> +                SHIFT_TOLERANCE);
Please remove the empty spaces here

2022-08-29 08:00 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
> +            }
I think now you can remove try/catch block

2022-08-29 08:00 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
>          } else {
Please remove the empty spaces here

2022-08-29 08:00 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
>          }
Please remove the empty spaces here

2022-08-29 08:00 UTC, TheMaskedTurtle commented on cse-cc-import-runner-app/src/main/java/com/farao_community/farao/cse/import_runner/app/dichotomy/DichotomyRunner.java
> +                fileImporter);
Please remove the empty spaces here

2022-08-29 09:28 UTC, TheMaskedTurtle approved these changes

2022-08-29 09:28 UTC, merged